# Generated by Django 4.2.7 on 2023-11-07 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('BL', 'Bloqued'), ('TE', 'Terminated')], default='AC', max_length=2)),
                ('pin', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(default='AC', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='client.client'),
        ),
    ]
