# Generated by Django 4.2.7 on 2023-11-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('BL', 'Bloqued'), ('TE', 'Terminated')], default='AC', max_length=2),
        ),
    ]
