# Generated by Django 4.2.7 on 2023-11-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_account_balance_alter_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
    ]
