# Generated by Django 4.2.7 on 2023-11-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_account_expenses_card_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='income',
        ),
        migrations.AddField(
            model_name='account',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
