# Generated by Django 4.2.7 on 2023-11-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_card_income_account_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, upload_to='card/%Y/%m/%d/'),
        ),
    ]
