# Generated by Django 4.2.7 on 2023-11-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_account_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
