# Generated by Django 4.2.7 on 2023-11-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_card_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='avatar',
            field=models.ImageField(blank=True, default='static/img/card.png', upload_to='card/%Y/%m/%d/'),
        ),
    ]
