# Generated by Django 4.2.7 on 2023-11-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_card_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='avatar',
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, default='static/img/card.png', upload_to='card/%Y/%m/%d/'),
        ),
    ]
