# Generated by Django 4.2.7 on 2023-11-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, default='card.png', upload_to='card/%Y/%m/%d/'),
        ),
    ]
