# Generated by Django 4.2.7 on 2023-11-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='concept',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
