# Generated by Django 4.2.7 on 2023-11-17 21:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_concept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('INC', 'Incomming'), ('OUT', 'Outgoing'), ('PAY', 'Payment')], max_length=3),
        ),
        migrations.CreateModel(
            name='Comission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('INC', 'Incomming Transaction'), ('OUT', 'Outgoing Transaction'), ('PAY', 'Payment')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name=django.core.validators.MinValueValidator(Decimal('0.01')))),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissions', to='transactions.transaction')),
            ],
        ),
    ]
