# Generated by Django 4.2.10 on 2024-02-13 19:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_kind_comission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comission',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='comission',
            name='kind',
            field=models.CharField(choices=[('INC', 'Incomming Transaction'), ('OUT', 'Outgoing Transaction'), ('PAY', 'Payment')], max_length=3, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='agent',
            field=models.CharField(max_length=120, verbose_name='agent'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='concept',
            field=models.CharField(blank=True, max_length=120, verbose_name='concept'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('INC', 'Incomming'), ('OUT', 'Outgoing'), ('PAY', 'Payment')], max_length=3, verbose_name='kind'),
        ),
    ]
